# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "endpoint-gen"
version = "0.1.4"
edition = "2021"
repository = "https://github.com/pathscale/EndpointGen/"
description = "Generate Rust code for websocket API endpoints"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
eyre = "0.6"
convert_case = "0.6.0"
itertools = "0.12"
regex = "1.5.4"
clap = "4.5.16"
futures = "0.3.30"
rustls-pemfile = "2.1.3"
tokio = { version = "1.39.3", features = ["full"]}
tracing = "0.1.40"
tracing-log = "0.2.0"
tracing-subscriber = "0.3.18"
tokio-cron-scheduler = "0.11.0"
dashmap = "6.0.1"
tokio-tungstenite = "0.23.1"
tokio-postgres = "0.7.11"
bytes = "1.7.1"
ethers = "2.0.14"
chrono = "0.4.38"
urlencoding = "2.1.3"
tokio-rustls = "0.26.0"
log-panics = "2.1.0"

